FROM node:20

# Set working directory inside container
WORKDIR /app/theme/static_src

# Copy only package.json and package-lock.json first
COPY theme/static_src/package*.json ./

# Install dependencies
RUN npm install

# Expose Tailwind dev server port
EXPOSE 5173

# Run Tailwind dev server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
