# Generated by Django 5.2.7 on 2025-10-22 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('business_type', models.CharField(blank=True, max_length=50, null=True)),
                ('business_status', models.CharField(blank=True, max_length=50, null=True)),
                ('umkm_incentive', models.CharField(blank=True, max_length=10, null=True)),
                ('omzet', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('usaha', 'Beban Usaha Lainnya'), ('lain', 'Beban Lain-lain')], default='usaha', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('total', models.BigIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='core.financialreport')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.financialreport')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('report', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RevenueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_type', models.CharField(choices=[('usaha', 'Pendapatan dari Usaha'), ('lain', 'Pendapatan Lain-lain')], default='usaha', max_length=10)),
                ('name', models.CharField(help_text="Used for 'Pendapatan Lain-lain' description", max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('selling_price', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_entries', to='core.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_items', to='core.financialreport')),
            ],
        ),
        migrations.CreateModel(
            name='HppEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AWAL', 'Persediaan Awal Bahan Baku'), ('PEMBELIAN', 'Pembelian Bahan Baku'), ('AKHIR', 'Persediaan Akhir Bahan Baku')], max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('harga_satuan', models.BigIntegerField(default=0)),
                ('diskon', models.BigIntegerField(default=0)),
                ('retur_qty', models.IntegerField(default=0)),
                ('ongkir', models.BigIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_entries', to='core.financialreport')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_entries', to='core.product')),
            ],
            options={
                'ordering': ['product__name', 'category'],
                'unique_together': {('report', 'product', 'category')},
            },
        ),
    ]
