# Generated by Django 5.2.7 on 2025-10-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_revenueitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenueitem',
            name='description',
        ),
        migrations.AlterField(
            model_name='revenueitem',
            name='name',
            field=models.CharField(blank=True, help_text="Product name (for 'usaha') or description (for 'lain')", max_length=255, null=True),
        ),
    ]
