# Generated by Django 5.2.7 on 2025-10-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_revenueitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='expense_category',
            field=models.CharField(choices=[('usaha', 'Beban Usaha Lainnya'), ('lain', 'Beban Lain-lain')], default='usaha', max_length=20),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='expense_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
