# Generated by Django 5.2.7 on 2025-10-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expenseitem_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='ptkp_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
