# Generated by Django 5.2.7 on 2025-10-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_financialreport_ptkp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hppentry',
            name='diskon',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hppentry',
            name='ongkir',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hppentry',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hppentry',
            name='retur_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
