# Generated by Django 5.2.7 on 2025-11-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_financialreport_ptkp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HppManufactureFinishedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FG_AWAL', 'Persediaan Barang Jadi Awal'), ('FG_AKHIR', 'Persediaan Barang Jadi Akhir')], max_length=20)),
                ('total', models.BigIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_manufaktur_fg', to='core.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_manufaktur_fg', to='core.financialreport')),
            ],
            options={
                'ordering': ['product__name', 'type'],
            },
        ),
        migrations.CreateModel(
            name='HppManufactureLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_manufaktur_labor', to='core.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_manufaktur_labor', to='core.financialreport')),
            ],
        ),
        migrations.CreateModel(
            name='HppManufactureMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BB_AWAL', 'Persediaan Bahan Baku Awal'), ('BB_AKHIR', 'Persediaan Bahan Baku Akhir'), ('BB_PEMBELIAN', 'Pembelian Bahan Baku')], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('harga_satuan', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_manufaktur_materials', to='core.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_manufaktur_materials', to='core.financialreport')),
            ],
            options={
                'ordering': ['product__name', 'type'],
            },
        ),
        migrations.CreateModel(
            name='HppManufactureOverhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_manufaktur_overhead', to='core.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_manufaktur_overhead', to='core.financialreport')),
            ],
        ),
        migrations.CreateModel(
            name='HppManufactureWIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WIP_AWAL', 'WIP Awal'), ('WIP_AKHIR', 'WIP Akhir')], max_length=20)),
                ('total', models.BigIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_manufaktur_wip', to='core.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_manufaktur_wip', to='core.financialreport')),
            ],
            options={
                'ordering': ['product__name', 'type'],
            },
        ),
    ]
