# Generated by Django 5.2.7 on 2025-11-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hppmanufacturefinishedgoods_hppmanufacturelabor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hppmanufacturematerial',
            name='diskon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hppmanufacturematerial',
            name='ongkir',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hppmanufacturematerial',
            name='retur_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hppmanufacturematerial',
            name='retur_qty',
            field=models.IntegerField(default=0),
        ),
    ]
