# Generated by Django 5.2.7 on 2025-10-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_hppentry_diskon_alter_hppentry_ongkir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hppentry',
            name='diskon',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hppentry',
            name='ongkir',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hppentry',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hppentry',
            name='retur_qty',
            field=models.IntegerField(default=0),
        ),
    ]
