# Generated by Django 5.2.7 on 2025-11-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hppmanufacturematerial_diskon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hppmanufacturematerial',
            name='nama_bahan_baku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
