# Generated by Django 5.2.7 on 2025-11-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hppmanufacturematerial_nama_bahan_baku'),
    ]

    operations = [
        migrations.AddField(
            model_name='hppmanufacturematerial',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
