# Generated by Django 5.2.7 on 2025-11-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hppmanufacturematerial_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hppmanufacturewip',
            name='harga_satuan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hppmanufacturewip',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hppmanufacturewip',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hppmanufacturewip',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
