# Generated by Django 5.2.7 on 2025-11-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_hppmanufacturewip_harga_satuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hppmanufacturelabor',
            name='harga_satuan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hppmanufacturelabor',
            name='jenis_tenaga_kerja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hppmanufacturelabor',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hppmanufacturelabor',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hppmanufacturelabor',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
