# Generated by Django 5.2.7 on 2025-11-06 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hppmanufacturelabor_harga_satuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hppmanufactureoverhead',
            name='harga_satuan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hppmanufactureoverhead',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hppmanufactureoverhead',
            name='nama_biaya',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hppmanufactureoverhead',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hppmanufactureoverhead',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='hppmanufactureoverhead',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.financialreport'),
        ),
        migrations.AlterField(
            model_name='hppmanufactureoverhead',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
