# Generated by Django 5.2.7 on 2025-11-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_hppmanufactureoverhead_harga_satuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hppmanufacturefinishedgoods',
            name='harga_satuan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hppmanufacturefinishedgoods',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hppmanufacturefinishedgoods',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hppmanufacturefinishedgoods',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
