# Generated by Django 5.2.7 on 2025-11-09 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_hppmanufacturefinishedgoods_harga_satuan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HppManufactureProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_diproduksi', models.IntegerField(default=0)),
                ('total_produksi', models.BigIntegerField(default=0)),
                ('hpp_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_manufaktur_production', to='core.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_manufaktur_production', to='core.financialreport')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
    ]
