# Generated by Django 5.2.7 on 2025-11-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_hppmanufactureproduction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hppmanufactureproduction',
            unique_together={('report', 'product')},
        ),
    ]
