# Generated by Django 5.2.7 on 2025-11-09 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_hppmanufactureproduction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='scope',
            field=models.CharField(choices=[('dagang', 'Dagang'), ('manufaktur', 'Manufaktur')], default='dagang', max_length=20),
        ),
    ]
