# Generated by Django 5.2.7 on 2025-11-11 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_expenseitem_product_expenseitem_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hppmanufactureoverhead',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpp_manufaktur_overhead', to='core.financialreport'),
        ),
    ]
