# Generated by Django 5.2.7 on 2025-11-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_hppmanufactureoverhead_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialreport',
            name='omzet',
        ),
        migrations.AddField(
            model_name='financialreport',
            name='omzet_status',
            field=models.CharField(blank=True, choices=[('iya', 'Iya'), ('tidak', 'Tidak')], help_text='Apakah omzet lebih dari 500 juta?', max_length=10, null=True),
        ),
    ]
