# Generated by Django 5.2.7 on 2025-11-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_financialreport_omzet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hppmanufacturefinishedgoods',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
